import React, { useMemo, useState } from "react";
import { _NewPage as Page, AppHeader } from "@dynatrace/strato-components-preview/layouts";
import { Heading, List, Text } from "@dynatrace/strato-components-preview/typography";
import { Button, Flex, Link, useCurrentTheme } from "@dynatrace/strato-components-preview";
import { DetailViewCard } from "./util/components/DetailViewCard";
import { CodeIcon, GroupIcon } from "@dynatrace/strato-icons";
import { MainViewCard } from "./util/components/MainViewCard";
import { getAppId } from "@dynatrace-sdk/app-environment";
import ChartsLayout from "./charts/ChartsLayout";
import DataImport from "./data_import/DataImport";

function useAppIconUrl(): string {
  const sdkAppId = useMemo(getAppId, []);
  return useMemo(() => {
    return sdkAppId === "local-dev-server"
      ? "http://localhost:3000/ui/assets/app-icon.png"
      : `/platform/app-engine/registry/v0.1/app-icons/${sdkAppId}`;
  }, [sdkAppId]);
}

export const App = () => {
  const theme = useCurrentTheme();
  const [isDataReady, setDataIsReady] = useState<boolean | undefined>();
  const appIconUrl = useAppIconUrl();

  return (
    <Page>
      <Page.Header>
        <AppHeader></AppHeader>
      </Page.Header>
      <Page.Main>
        <Flex flexDirection="column" padding={40} gap={16} maxWidth="960px" alignSelf={"center"}>
          <Flex flexDirection="row" width="100%" alignItems="center">
            <Flex flexDirection="column">
              <Heading>GitHub Actions Profiler</Heading>
              <Text>
                The GitHub Actions Profiler analyzes data generated by GitHub Actions workflows and
                provides valuable insights into their performance and efficiency. Through analyzing
                the workflows, teams can identify bottlenecks and optimize processes to improve
                build times, reduce errors, and increase efficiency.
              </Text>
              <Heading level={4}>This app demonstrates</Heading>
              <List ordered={false}>
                <Text>How business events can be used to analyze GitHub Actions workflows</Text>
                <Text>How notifications can be triggered by business events</Text>
                <Text>How to fetch data with Dynatrace Query Language (DQL)</Text>
                <Text>
                  How to create data visualizations using{" "}
                  <Link
                    href="https://developer.dynatrace.com/preview/reference/design-system/"
                    target="_blank"
                  >
                    Design System components
                  </Link>
                </Text>
              </List>
            </Flex>
            <Flex alignSelf={"flex-start"} padding={40}>
              <img src={appIconUrl} width="90px" height="90px" />
            </Flex>
          </Flex>
          <Flex flexDirection="column">
            {/* If there is no data yet in Grail, we show a UI with options how to ingest sample or real data */}
            {isDataReady ? <ChartsLayout /> : <DataImport setDataIsReady={setDataIsReady} />}
          </Flex>
          <MainViewCard>
            <Flex flexGrow={1}>
              <Flex alignSelf={"center"} flexDirection="column" gap={4}>
                <Heading level={6}>What's next?</Heading>
                <Text>Fork this app on GitHub and learn how to write apps for Dynatrace</Text>
              </Flex>
            </Flex>
            <Flex justifyContent="center">
              <Flex alignSelf={"center"}>
                {/* TODO: replace href with actual link to the repository */}
                <Button
                  as="a"
                  variant="accent"
                  color="primary"
                  href="https://www.google.at"
                  target="_blank"
                >
                  Fork on Github
                </Button>
                {/* <ExternalLink href="#">Fork on Github</ExternalLink> */}
              </Flex>
            </Flex>
          </MainViewCard>
        </Flex>
      </Page.Main>
      <Page.DetailView onDismiss={() => {}}>
        <Flex flexDirection="column" gap={16} paddingTop={40} paddingLeft={8} paddingRight={8}>
          <Heading level={4}>Ready to develop?</Heading>
          <Text>Learn to write apps with Dynatrace Developer and the Dynatrace community.</Text>
          <DetailViewCard
            href="https://developer.dynatrace.com/preview/getting-started/quickstart/"
            icon={
              theme === "light" ? (
                <img src={"./assets/dynatrace-logo-light.svg"} width="20px" />
              ) : (
                <img src={"./assets/dynatrace-logo-dark.svg"} width="20px" />
              )
            }
            headline="Learn to create apps"
            text="Dynatrace Developer shows you how"
          ></DetailViewCard>
          <DetailViewCard
            href="https://community.dynatrace.com/t5/Developers/ct-p/developers"
            icon={<GroupIcon />}
            headline="Join Dynatrace Community"
            text="Ask questions, get answers, share ideas"
          ></DetailViewCard>
          {/* TODO: replace href with actual link to the repository */}
          <DetailViewCard
            href="#"
            icon={<CodeIcon />}
            headline="Collaborate in GitHub"
            text="Start your own app by forking it on GitHub"
          ></DetailViewCard>
        </Flex>
      </Page.DetailView>
    </Page>
  );
};
